# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DgwUdhk2cDfp7uaiLYgB65v3l882Jw-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("USA_Housing.csv")

df.head(10)

df.info()

df.describe()

df.columns

sns.pairplot(df)

numeric_df = df.select_dtypes(include='number')
sns.heatmap(numeric_df.corr(),  annot=True, cmap='coolwarm')