# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vs5eh20oHZvqu5L7YuiB1ZGNRd19qrnE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = sns.load_dataset('penguins')
df.head(10)

df.shape

df.tail()

df.isnull().sum()

df.describe().T

df.describe()

df.dtypes

df.info()

df.describe(include='all')

df_numeric = df.select_dtypes(include=['number'])
df_numeric.corr()

sns.heatmap(df_numeric.corr(), cmap= 'Wistia', annot=True)

df.hist(figsize=(12,8))
plt.show()

df.plot(kind= 'box', subplots=True, layout=(3,2), sharex=False, sharey= False, figsize=(8,12))
plt.show()

df.sex.value_counts()

df.island.value_counts()

df.species.value_counts()

df.species.value_counts()

sns.countplot(data=df, x='sex', palette='summer')

sns.countplot(data=df, x='island', palette='RdPu')