# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier
from sklearn.datasets import make_blobs

# Generate data
X, y = make_blobs(n_samples=40, centers=2, random_state=42,
                 cluster_std=1.2)

# Train model (hinge loss = SVM)
model = SGDClassifier(loss="hinge", max_iter=1000)
model.fit(X, y)

# Plot points
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='bwr')

# Decision boundary
w = model.coef_[0]
b = model.intercept_[0]

x_vals = np.linspace(X[:, 0].min(), X[:, 0].max(), 100)
y_vals = -(w[0] * x_vals + b) / w[1]

plt.plot(x_vals, y_vals, 'k-')  # separating line
plt.title("Max Margin Hyperplane (SGD)")
plt.show()