# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pm_BTxjaSPS-Ta3ZNuMkf37m32l6sUh8
"""

# Import function to generate a synthetic classification dataset
!pip install numpy scikit-learn matplotlib pandas
from sklearn.datasets import make_classification

# Import matplotlib for plotting graphs
from matplotlib import pyplot as plt

# Import logistic Regression model
from sklearn.linear_model import LogisticRegression

# Import function to split data into training and testing sets
from sklearn.model_selection import train_test_split

# Import confusion matrix for evaluation
from sklearn.metrics import confusion_matrix

# Import pandas (not used here but useful for data handling)
import pandas as pd


# Generate a synthetic dataset for binary classification
# n_samples = total number of data points
# n_features = number of input features
# n_classes = number of output classes (0 and 1)
# n_clusters_per_class = clusters per class
# flip_y = adds noise (3% labels flipped)
# n_informative = useful features
# n_redundant = useless duplicate features
# n_repeated = repeated features
x, y = make_classification(
    n_samples = 100,
    n_features = 1,
    n_classes = 2,
    n_clusters_per_class = 1,
    flip_y = 0.03,
    n_informative = 1,
    n_redundant = 0,
    n_repeated = 0
)

# Create a scatter plot of the dataset
# x values on x-axis, y values determine color
plt.scatter(x, y, c = y, cmap = 'rainbow')

# Add title to the plot
plt.title("Scatter plot of Logistic Regression")

# Display the plot
plt.show()


# Split the dataset into training and testing sets
# random_state ensures same split every time
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 1)

# Create a Logistic Regression model
log_reg = LogisticRegression()

# Train the model using training data
log_reg.fit(x_train, y_train)

# Print the coefficient (slope) learned by the model
print(log_reg.coef_)

# Print the intercept (bias term)
print(log_reg.intercept_)

# Predict class labels for test data
y_pred = log_reg.predict(x_test)

# Print predicted values
print(y_pred)