# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1auHUYt9mu1IiO1GsdoTfFIOvr_O07Vhq
"""

# Importing the pandas library, which is used for data manipulation and analysis.
# It helps in reading datasets (like CSV files) and managing them in table format (DataFrame).
import pandas as pd

# Importing pyplot module from matplotlib, which is used for creating graphs and visualizations.
# It helps to draw plots like scatter plots (scatter plot).
from matplotlib import pyplot as plt

# Importing math module to perform mathematical operations
# like exponent (used in sigmoid function later).
import math

# Reading the CSV file named 'insurance_data.csv' and storing
# it in a DataFrame called df.
# A DataFrame is like a table with rows and columns.
df = pd.read_csv('insurance_data.csv')

# Displaying the first 5 rows of the dataset to understand its
# structure and values.
df.head()

# Creating a scatter plot graph:
# df.age is plotted on the x-axis (independent variable)
# df.bought_insurance is plotted on the y-axis (dependent variable: 0 or 1)
# marker='+' means each point will be shown as a plus symbol
# color='red' sets the color of the points
# This helps visualize how age relates to buying insurance.
plt.scatter(df.age, df.bought_insurance, marker='+', color='red')

# Importing train_test_split function to divide the dataset
# into training and testing sets.
# This is important to evaluate how well the model performs on unseen data.
from sklearn.model_selection import train_test_split

# Splitting the dataset into training and testing sets
# df['age'] -> input feature (independent variable)
# df['bought_insurance'] -> target/output variable (dependent)
# train_size = 0.8 means 80% data for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(df[['age']], df.bought_insurance, train_size=0.8)

# Printing the test dataset (ages) to see which values the model will predict on.
print(X_test)

# Importing LogisticRegression model from sklearn.
# This model is used when the output classification (output) is 0 or 1.
from sklearn.linear_model import LogisticRegression

# Creating an instance of the logistic regression model.
model = LogisticRegression()

# Training (fitting) the model using the training data.
# The model learns the relationship between age and buying insurance.
model.fit(X_train, y_train)

# Predicting the output (0 or 1) for the test data.
# This returns a list of predictions.
y_predicted = model.predict(X_test)

# Again predicting using the same function (this line is redundant but shown here for practice).
model.predict(X_test)

# Calculating the accuracy of the model.
# It