# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TM1MHTDIHH9QEZZtKxVE7ePCMO8GZ4Tv
"""

# Importing necessary libraries

# Importing NumPy for numerical operations and array handling
import numpy as np

# Importing Matplotlib for plotting graphs and visualizations
import matplotlib.pyplot as plt

# Importing Logistic Regression model from sklearn
from sklearn.linear_model import LogisticRegression

# Importing built-in datasets module from sklearn
from sklearn import datasets

# Loading the Iris dataset (contains features and target labels of flowers)
iris = datasets.load_iris()

# Selecting only the first two features (sepal length and sepal width)
# This is done so we can easily visualize the decision boundary in 2D
X = iris.data[:, :2]

# Extracting the target labels (0 = setosa, 1 = versicolor, 2 = virginica)
Y = iris.target

# Creating an instance of the Logistic Regression model
# 'multi_class="auto"' automatically handles multi-class classification
logreg = LogisticRegression(multi_class='auto', max_iter=200)

# Training the model using the feature data (X) and corresponding labels (Y)
logreg.fit(X, Y)

# Finding minimum and maximum values of first feature (with padding of 0.5)
x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5

# Finding minimum and maximum values of second feature (with padding of 0.5)
y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5

# Defining step size for mesh grid (smaller value = smoother boundary but more computation)
h = 0.02

# Creating a mesh grid (a grid of points covering the entire feature space)
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))

# Predicting class labels for each point in the mesh grid
# np.c_ combines the x and y coordinates into pairs for prediction
Z = logreg.predict(np.c_[xx.ravel(), yy.ravel()])

# Reshaping the prediction results to match the shape of the mesh grid
Z = Z.reshape(xx.shape)

# Creating a figure with a fixed size
plt.figure(figsize=(6, 4))

# Plotting the decision boundary using colored regions
plt.pcolormesh(xx, yy, Z, cmap=plt.cm.Paired, shading='auto')

# Plotting the original data points on top of the decision boundary
# edgecolors='k' gives black border to points
plt.scatter(X[:, 0], X[:, 1], c=Y, edgecolors='k', cmap=plt.cm.Paired)

# Labeling the x-axis
plt.xlabel('Sepal length')

# Labeling the y-axis
plt.ylabel('Sepal width')

# Setting limits for x-axis
plt.xlim(xx.min(), xx.max())

# Setting limits for y-axis
plt.ylim(yy.min(), yy.max())

# Removing tick marks for cleaner visualization
plt.xticks(())
plt.yticks(())

# Displaying the plot
plt.show()

# Calculating and printing the accuracy of the model on training data
print("Model Accuracy:", logreg.score(X, Y))