# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

# Dataset
X = np.array([[22,15000],
              [25,18000],
              [47,52000],
              [52,60000],
              [46,58000]])

Y = np.array([0, 0, 1, 1, 1])

# Preprocessing (Scaling)
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Train model
model = LogisticRegression()
model.fit(X_scaled, Y)

# Predictions
Y_pred = model.predict(X_scaled)

print("Predictions:", Y_pred)

# Plot (using Age vs Bought for visualization)
plt.scatter(X_scaled[:,0], Y)

# Plot decision boundary (approx line)
x_values = np.linspace(0,1,100)
y_values = model.predict(np.column_stack((x_values, x_values)))
plt.plot(x_values, y_values)

plt.xlabel("Scaled Age")
plt.ylabel("Bought (0/1)")
plt.title("Classification Graph")

plt.show()