# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Extra Mimo Activity Housing data

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

housing = fetch_california_housing()

x = housing.data
y = housing.target

x = x[:, np.newaxis, 2]

x_train = x[:-50]
x_test = x[-50:]

y_train = y[:-50]
y_test = y[-50:]

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Coefficient: ", model.coef_)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("R2 Score: %.2f" % r2_score(y_test, y_pred))

plt.scatter(x_test, y_test, color='black')
plt.plot(x_test, y_pred, color='blue', linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()