# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-X7MsOdqY1K9gSZlPu16tsZZmrSTgLN
"""

from numpy import asarray          # Used to convert normal Python lists into NumPy arrays (needed for vector operations)
from numpy import arange           # Used to generate evenly spaced numbers (like range but supports decimals)
from numpy.random import rand      # Generates random numbers between 0 and 1
from matplotlib import pyplot      # Library used for plotting graphs

# objective function
def objective(x):
    return x**2.0                  # Function we want to minimize → f(x) = x^2 (a bowl-shaped curve, minimum at x = 0)

# derivative of objective function
def derivative(x):
    return x * 2.0                 # Derivative of x^2 is 2x → tells slope (direction + steepness)

# gradient descent algorithm
def gradient_descent(objective, derivative, bounds, n_iter, step_size):

    solutions, scores = list(), list()
    # 'solutions' will store all x values visited
    # 'scores' will store corresponding f(x) values

    # generate an initial point
    solution = bounds[:, 0] + rand(len(bounds)) * (bounds[:, 1] - bounds[:, 0])
    # Step-by-step:
    # bounds[:, 0] → lower bound (e.g., -1)
    # bounds[:, 1] → upper bound (e.g., 1)
    # rand(...) → random number between 0 and 1
    # So this picks a random starting point between -1 and 1
    # IMPORTANT: Gradient descent usually starts from a random guess

    # run the gradient descent
    for i in range(n_iter):        # Loop runs 'n_iter' times (each loop = one step downhill)

        gradient = derivative(solution)
        # Compute slope at current point
        # If slope is positive → move left
        # If slope is negative → move right

        solution = solution - step_size * gradient
        # Core idea of gradient descent:
        # new_x = old_x - (learning_rate * slope)
        # We subtract because we want to move "downhill"
        # step_size controls how big each step is

        solution_eval = objective(solution)
        # Evaluate how good this solution is (calculate f(x))

        solutions.append(solution)
        # Store current x value

        scores.append(solution_eval)
        # Store corresponding function value

        print('>%d f(%s) = %.5f' % (i, solution, solution_eval))
        # Print progress:
        # i → iteration number
        # solution → current x
        # solution_eval → current f(x)

    return [solutions, scores]
    # Return all visited points and their values

# define range for input
bounds = asarray([[-1.0, 1.0]])
# Search space → x can be between -1 and 1

# define the total iterations
n_iter = 30
# Number of steps gradient descent will take
# More iterations → better chance to reach minimum

# define the step size
step_size = 0.1
# Learning rate:
# Small → slow but stable
# Large → fast but may overshoot

# perform the gradient descent search
solutions, scores = gradient_descent(objective, derivative, bounds, n_iter, step_size)
# Run algorithm and collect all steps taken

# sample input range uniformly at 0.1 increments
inputs = arange(bounds[0,0], bounds[0,1]+0.1, 0.1)
# Create values like: -1.0, -0.9, ..., 1.0
# Used for plotting the actual function curve

# compute targets
results = objective(inputs)
# Apply f(x) = x^2 to all input values to get curve points

# create a line plot of input vs result
pyplot.plot(inputs, results)
# Plot the actual function curve (parabola)

# plot the solutions found
pyplot.plot(solutions, scores, '.-', color='red')
# Plot the path taken by gradient descent
# '.' → points
# '-' → line connecting them
# red → highlight optimization path

# show the plot
pyplot.show()
# Display the final graph