
CREATE TABLE IF NOT EXISTS NOBEL_WIN (
  YEAR INTEGER,
  SUBJECT TEXT,
  WINNER TEXT,
  COUNTRY TEXT,
  CATEGORY TEXT
);

INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
  (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCEINTIST'),
  (1970, 'PHYSICS', 'LOUIS NEEL', 'FRANCE', 'SCEINTIST'),
  (1971, 'PHYSICS', 'PAUL', 'FRANCE', 'SCEINTIST'),
  (1971, 'CHEMISTRY', 'HAMILTON', 'SWEDEN', 'LINGUIST'),
  (1972, 'LITERATURE', 'BERNAND KELSON', 'GERMANY', 'ECONOMIST'),
  (1972, 'ECONOMICS', 'JOSEPH', 'RUSSIA', 'ECONOMIST'),
  (1973, 'BIOLOGY', 'PHILIPS', 'USA', 'PRIME MINISTER'),
  (1980, 'BIOLOGY', 'MARTIN', 'USA', 'PRESIDENT'),
  (1981, 'PHYSIOLOGY', 'HANNAH', 'HUMGARY', 'SCIENTIST'),
  (1975, 'PHYSICS', 'PETER', 'CHILE', 'SCIENTIST');

SELECT * FROM NOBEL_WIN;

SELECT * FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';