# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wHCiNyUfgic84wTxNVKEURnWVeF3Qsw
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("country_vaccinations.csv")
df.head(10)

df.isnull().sum()

df.isnull().any()

# Visualize missing values using a heatmap (optimize by using a subset of data)
subset = df.iloc[:5200, :] # Taking the first 100 rows for better perfomance
plt.figure(figsize=(12, 8))
sns.heatmap(subset.isnull(), cbar=False, cmap="viridis")
plt.show()

df.dropna()

df.dropna(how="all")

df.fillna(0)

df.fillna(method="bfill")

df.fillna(method="ffill")

df.interpolate()

df_dropped=df.dropna()
df_dropped